### ISSUE TITLE
Ability to set branding theme

### ISSUE THREAD

**Issue by dbryar** [pingidentity/terraform-provider-pingone#357] opened 2023-05-15 05:41 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
There is currently no obvious way to set the default theme in the brand settings, or using the branding template

### New or Affected Resource(s)
- pingone_branding_theme

#### Schema
[Read-Only]
- default) (Boolean) Specifies whether this theme is the environment's default branding configuration.

### Potential Terraform Configuration

Allow the `default` flag to be set true and if `default === true` Terraform should mark the theme as default for the environment.

The flag is set in the API as `mutable` and so it should be in Terraform as well

### References

https://apidocs.pingidentity.com/pingone/platform/v1/api/#branding

**Comment by patrickcping** [comment] 2023-05-15 08:37
Hey @dbryar thanks for raising!  This is a duplicate of #310 (which is currently planned for the v0.15.0 release - tracked in the issue milestones) so I'm closing this issue out.  I've added some of the context from this issue to the other.

**Closed by patrickcping** 2023-05-15 08:37 UTC
Labels: duplicate, type/enhancement, service/base
